name: "gha-dkim"
description: " Github Action for continuous deployment with dkim authentication"
inputs:
  server:
    description: "The target server"
    required: true
  file_to_deploy:
    description: "The artefact to deploy"
    required: true
  signing_address:
    description: "The signing address eg foo@example.com (requires foo._domain.example.com to contain the dkim public key)"
    required: true
  pem_private_key_path:
    description: "Path to the PEM private key file for DKIM signing"
    required: false
    default: "/tmp/a.pem"

runs:
  using: "composite"
  steps:
    - name: requirements
      shell: "bash"
      run: |
        pip install --upgrade dkimpy

    - name: deploy
      id: deploy
      shell: "bash"
      run: |
        python ${{ github.action_path }}/deploy.py \
          --server ${{ inputs.server }} \
          --file_to_deploy ${{ inputs.file_to_deploy }} \
          --signing_address ${{ inputs.signing_address }} \
          --pem_private_key_path ${{ inputs.pem_private_key_path }}
